source 'https://rubygems.org'

gem 'rspec'
gem 'selenium-webdriver', '~> 2.53'
gem 'require_all'
gem 'parallel_split_test'
gem 'sauce_whisk'
gem 'rake'
gem 'json', '~> 1.0'
gem 'appium_lib', '~> 2.0'
gem 'eyes_selenium'
